name: Running Testinette using Vitest
on:
  push:

permissions:
  contents: write

jobs:
  run-testinette:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ghcr.io/edenschoolfrance/exam_a1-1javascript:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace }}:/app/src
      options: --cpus 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Remove optional export keyword
        run: sed -i 's/export function/function/g' /app/src/*
      - name: Add export keyword
        run: sed -i 's/function/export function/g' /app/src/*
      - name: Running testinette
        run: cd /app && npm run test
